- name: Recreate
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Remove
      block:
        - name: Remove docker container
          docker_container:
            name: 'vidmem_bot'
            state: absent

        - name: Remove docker image
          docker_image:
            name: "{{ DOCKER_USERNAME }}/vidmem_bot:latest"
            state: absent
      become: yes
      become_user: root

    - name: Install
      block:
        - name: Docker login
          docker_login:
            email: '{{ EMAIL }}'
            username: "{{ DOCKER_USERNAME }}"
            password: "{{ DOCKER_PASSWORD }}"

        - name: Запуск контейнера
          docker_container:
            name: 'vidmem_bot'
            image: '{{ DOCKER_USERNAME }}/vidmem_bot:latest'
            restart_policy: unless-stopped
            state: started
            pull: yes
            network_mode: host
            env:
              API_TOKEN: "{{ BOT_TOKEN }}"
              ADMIN_ID: "{{ ADMIN_ID }}"
              CHANNEL_ID: "{{ CHANNEL_ID }}"
              SUGG_ID: "{{ SUGG_ID }}"
              MONGODB_URL: "{{ MONGO_URL }}"
              WEBAPP_HOST: "{{ WEBAPP_HOST }}"
              WEBAPP_PORT: "{{ WEBAPP_PORT }}"
              WEBHOOK_URL: "{{ WEBHOOK_URL }}"
              INST_LOGIN: "{{ INST_LOGIN }}"
              INST_PASS: "{{ INST_PASS }}"

      become: yes
      become_user: root
