- name: Recreate
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Remove
      block:
        - name: Remove docker container
          docker_container:
            name: 'vidmem_bot'
            state: absent

        - name: Remove docker image
          docker_image:
            name: '{{username}}/vidmem_bot:latest'
            state: absent
      become: yes
      become_user: root

    - name: Install
      block:
        - name: Docker login
          docker_login:
            email: '{{email}}'
            username: '{{username}}'
            password: '{{password}}'

        - name: Запуск контейнера
          docker_container:
            name: 'vidmem_bot'
            image: '{{username}}/vidmem_bot:latest'
            restart_policy: unless-stopped
            state: started
            pull: yes
            network_mode: host
            env:
              API_TOKEN: "{{ token }}"
              ADMIN_ID: "{{ admin_id }}"
              CHANNEL_ID: "{{ channel_id }}"
              SUGG_ID: "{{ sugg_id }}"
              MONGODB_URL: "{{ mongo }}"
              WEBAPP_HOST: "{{ app_host }}"
              WEBAPP_PORT: "{{ app_port }}"
              WEBHOOK_URL: "{{ webhook }}"

      become: yes
      become_user: root