- name: Recreate
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Remove
      block:
        - name: Remove docker container
          docker_container:
            name: '{{ BOT_NAME | lower }}'
            state: absent

        - name: Remove docker image
          docker_image:
            name: "{{ DOCKER_USERNAME }}/{{ BOT_NAME | lower }}:latest"
            state: absent
      become: yes
      become_user: root

    - name: Install
      block:
        - name: Docker login
          docker_login:
            email: '{{ EMAIL }}'
            username: "{{ DOCKER_USERNAME }}"
            password: "{{ DOCKER_PASSWORD }}"

        - name: Запуск контейнера
          docker_container:
            name: '{{ BOT_NAME | lower }}'
            image: '{{ DOCKER_USERNAME }}/{{ BOT_NAME | lower }}:latest'
            restart_policy: unless-stopped
            state: started
            pull: yes
            network_mode: host
            env:
              BOT_NAME: "{{ BOT_NAME | lower }}"
              WATERMARK_TEXT: "{{ WATERMARK_TEXT }}"

              API_TOKEN: "{{ BOT_TOKEN }}"
              ADMIN_ID: "{{ ADMIN_ID }}"
              CHANNEL_ID: "{{ CHANNEL_ID }}"
              SUGG_ID: "{{ SUGG_ID }}"

              DB_URL: "{{ DB_URL }}"
              CACHE_URL: "{{ CACHE_URL }}"

              WEBAPP_HOST: "{{ WEBAPP_HOST }}"
              WEBAPP_PORT: "{{ WEBAPP_PORT }}"
              WEBHOOK_URL: "{{ WEBHOOK_URL }}"

              INST_LOGIN: "{{ INST_LOGIN | default('')}}"
              INST_PASS: "{{ INST_PASS | default('')}}"

      become: yes
      become_user: root
