name: recreate bot
on: [workflow_dispatch]
jobs:
  build:
    name: Copy
    runs-on: ubuntu-latest
    steps:
    - name: view the secrets context
      shell: bash
      run: echo "$SECRETS_CONTEXT"
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}

    - name: view
      shell: bash
      run: echo "$SECRETS_CONTEXT"
      env:
        SECRETS_CONTEXT: ${{ secrets }}

    - uses: actions/checkout@master
    - name: copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: 22
        source: "bot.deploy.yml"
        target: "~/playbooks"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: 22
        script: ansible-playbook ~/playbooks/bot.deploy.yml --extra-vars "secrets=${{ secrets }}"
