name: recreate bot
on: [workflow_dispatch]
jobs:
  build:
    name: Copy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: 22
        source: "bot.deploy.yml"
        target: "~/playbooks"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: 22
        script: ansible-playbook ~/playbooks/bot.deploy.yml --extra-vars "email=${{ secrets.EMAIL }} password=${{ secrets.DOCKER_PASSWORD }} username=${{ secrets.DOCKER_USERNAME }} token=${{ secrets.BOT_TOKEN }} admin_id=${{ secrets.ADMIN_ID }} channel_id=${{ secrets.CHANNEL_ID }} sugg_id=${{ secrets.SUGG_ID }} mongo=${{ secrets.MONGO_URL }} app_host=${{ secrets.WEBAPP_HOST }} app_port=${{ secrets.WEBAPP_PORT }} webhook=${{ secrets.WEBHOOK_URL }}"
